version: 2
jobs:
  build:
    working_directory: ~/Desktop/Play-ground/hackerbay/
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: test
          command: npm run coverage